### Welcome to Hexo-Theme-Lx
### Author:blleng(https://github.com/blleng)
### Adder:186526(https://github.com/186526)
###Version:v0.3.9+
version: 0.3.9

# favicon
favicon: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/favicon.ico
# Theme-color for Android Chrome
theme_color: "#58b77a"

# personal information
personal_des: "Hexo-Theme-LX"

# avatar
avatar: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/images/avatar.jpeg

###The options below are images information
# Home cover
cover: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/images/cover.jpeg
# page cover
postcover: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/images/post_cover.jpeg
# the cover of newer or older post
pre_post: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/images/footer-r.jpeg
nex_post: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/images/footer-l.jpeg

# The theme of sidebar
##pure color：green,red,blue,bnp(bright neon pink),orange,black,pink,gol-b(golden brown),greenish(greenish blue)
##gradient color：endless-river,crazy-orange,between-clouds,amethyst,steel-man,d2f(dance to forget),park-life,moonlit,fb-messenger,flickr
## default: black-grey
menu_theme: greenish

# menu content
menu:
  category: true #category
  pages:  #the page created by yourself
    enable: true
    links:
      'Guestbook': guestbook/
      'About': about/
  friends:
    enable: true
    links:
      Theme-LX: 
        url: https://lx.js.org/
        img: https://lx.js.org/favicon.ico
  tool:
    enable: false
    links:
      Tool: tool/
# social links
#
#links:
#  name:
#   icon: fontawesome icon
#   link: url
social:
  enable: true
  links:
  #  GitHub:
  #    icon: github
  #    link: https://github.com/yourname
  #  Email:
  #    icon: envelope
  #    link: mailto:yourname@youremailaddress
  #  Instagram:
  #    icon: instagram
  #    link: https://instagram.com/yourname

# local search
#install first:
#'npm install hexo-generator-searchdb -s'
local_search:
  enable: false
  trigger: auto #'auto' or 'manual' 
  top_n_per_article: 1
  unescape: false
  preload: true
  placeholder: Search...

# footer
footer:

# Analytics
google_analytics: #Google ID
baidu_analytics: #Baidu ID

# Lx use valine as comment system
# You should create an application in Leancloud to get the appid and appkey
comment:
  enable: false
  appid: ''
  appkey: ''
  notify: false
  verify: false
  placeholder: 'Say something.' 
  avatar: identicon
  guest_info: nick,mail,link
  pageSize: 10
  language: en
  cdn: https://cdn.jsdelivr.net/gh/186526/jsdelivr/Valine.min.js

# Mathjax
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/3.0.5/es5/tex-mml-svg.js

# FontAwesome-CDN
font_awesome: https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

# Font
font:
  enable: true
  host: https://fonts.loli.net
  codes: ##the font for codes
    enable: true
    family: Fira Code
  else:  ##the font for others
    enable: false
    family: Noto Serif SC

########### Develop Options ############
############# Warning ##################
####### Don't edit options below #######
## unless you know what you are doing ##
############# Warning ##################



#The dir of Js and Css
base_file:
  jquery_cdn: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  js: https://cdn.jsdelivr.net/npm/theme-lx@0.3.9/source/js/
  css: https://cdn.jsdelivr.net/gh/186526/jsdelivr/

#develop mode
#If true，`lx` will load js and css from local `source` dir.
#Local css file---> themes/lx/source/main.styl
#Local js file dir---> themes/lx/sourc/js/
develop: false